version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/sangtech-deploy-folder
permissions:
  - object: /home/ubuntu/sangtech-deploy-folder
    owner: ubuntu
    group: ubuntu
    mode: 755
